import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(HERE, '../..')
const OUT = path.join(ROOT, 'assets/readme')
const items = JSON.parse(fs.readFileSync(path.join(HERE, 'items.json'), 'utf8'))
const facts = JSON.parse(fs.readFileSync(path.join(OUT, 'facts.json'), 'utf8'))

const esc = value => String(value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')

function picture(base, alt) {
  return `<picture>
<source media="(max-width: 500px) and (prefers-color-scheme: dark)" srcset="assets/readme/${base}-narrow-dark.svg">
<source media="(max-width: 500px)" srcset="assets/readme/${base}-narrow-light.svg">
<source media="(prefers-color-scheme: dark)" srcset="assets/readme/${base}-dark.svg">
<img alt="${esc(alt)}" src="assets/readme/${base}-light.svg" width="100%">
</picture>`
}

function cardPicture(item) {
  const base = `card-${item.id}`
  return `<a href="${esc(item.url)}">
<picture>
<source media="(max-width: 500px) and (prefers-color-scheme: dark)" srcset="assets/readme/${base}-narrow-dark.svg">
<source media="(max-width: 500px)" srcset="assets/readme/${base}-narrow-light.svg">
<source media="(prefers-color-scheme: dark)" srcset="assets/readme/${base}-dark.svg">
<img alt="${esc(`${item.index}. ${item.title}. ${item.copy}`)}" src="assets/readme/${base}-light.svg" width="100%">
</picture>
</a>`
}

const cardRows = []
for (let index = 0; index < items.length; index += 2) {
  const pair = items.slice(index, index + 2)
  cardRows.push(`<tr>
${pair.map(item => `<td width="50%">${cardPicture(item)}</td>`).join('\n')}
</tr>`)
}
const cardsHtml = `<table>
${cardRows.join('\n')}
</table>`

const markdown = `<!-- generated by scripts/readme/build.mjs. do not edit by hand. -->

${picture('masthead', 'DSH Branchline routes the current remote default branch into isolated DSH tasks while the primary checkout stays untouched.')}

DSH Branchline gives [DeepSeek Harness](https://github.com/deepseek-ai/deepseek-harness) a clean start for every task: fetch the remote default branch, pin its exact commit, then open an isolated worktree as a native DSH Workspace and Session.

## Install

\`\`\`powershell
git clone https://github.com/ryanportfolio/dsh-branchline.git
cd dsh-branchline
.\\setup.ps1
.\\Start-Branchline.cmd
\`\`\`

Requires Windows, Git 2.38+, Node 22.19+, and DeepSeek Harness 0.1.x. The plugin itself remains portable; the bundled control-panel launcher targets Windows PowerShell 5.1 and PowerShell 7.

## Why Branchline exists

DSH normally starts in the repository folder you select. A dirty or stale checkout is a poor base for a new coding task, so Branchline fetches \`origin/HEAD\`, pins its exact commit, and opens a separate linked worktree.

The unofficial [dsh-worktree](https://github.com/Eleven-is-cool/dsh-worktree) creates worktrees from local branches. Branchline also needed durable task state, validation, review, and recovery. Its task-board foundation derives from [Palaiologos1453's MIT-licensed Worktree Studio](https://github.com/Palaiologos1453/dsh-worktree-studio); the launcher and fresh-origin workflow were built for Branchline.

${picture('route', 'Fetch the remote default, create an isolated checkout, open a native DSH session, and keep the branch for review.')}

${cardsHtml}

## Use

1. Start the launcher and choose any local Git repository.
2. Open **Worktree tasks** in the DSH sidebar.
3. Create a task with **Base ref** empty.
4. Work in the new DSH Session. Your primary checkout stays on its current branch with its current files.
5. Review the task, then push its dsh/* branch or open a pull request through your normal Git workflow.

## Verified surface

${facts.tests} tests across ${facts.testFiles} files · ${facts.dependencies} runtime dependency · PowerShell 5.1 and 7 launcher self-tests · local delivery disabled by default

## Docs

- [Usage and configuration](docs/usage.md)
- [Architecture and safety model](docs/architecture.md)
- [Security policy](SECURITY.md)
- [Contributing](CONTRIBUTING.md)
- [Changelog](CHANGELOG.md)

## Licence and credit

[MIT](LICENSE). See [NOTICE](NOTICE) for the exact upstream-derived boundary and retained credit.
`

let failures = 0
const fail = message => { console.error(`FAIL README: ${message}`); failures += 1 }
if (!markdown.startsWith('<!-- generated by scripts/readme/build.mjs. do not edit by hand. -->')) fail('generated marker missing')
for (const required of ['## Install', '## Use', '## Licence and credit', '.\\setup.ps1', '.\\Start-Branchline.cmd', 'docs/usage.md', 'NOTICE', 'Palaiologos1453/dsh-worktree-studio']) {
  if (!markdown.includes(required)) fail(`required content missing: ${required}`)
}
for (const item of items) {
  const hits = cardsHtml.split(`href="${item.url}"`).length - 1
  if (hits !== 1) fail(`${item.id} card link count is ${hits}`)
}
for (const match of markdown.matchAll(/(?:src|srcset)="(assets\/readme\/[^"]+)"/gu)) {
  if (!fs.existsSync(path.join(ROOT, match[1]))) fail(`missing asset ${match[1]}`)
}
if (/[A-Z]:\\\\Users\\\\[^\\\\\s]+|[\w.+-]+@gmail\.com/iu.test(markdown)) fail('private path or identity found')
if (failures > 0) process.exit(1)

fs.writeFileSync(path.join(ROOT, 'README.md'), markdown)
process.stdout.write(`README: ${markdown.split(/\r?\n/u).length} lines; cards: ${items.length}\n`)
